deb for syncthing
Arsen6331/lure-repo pull request #14
Opened 2022-11-05 20:50 UTC by xpamych

2022-11-06 03:11 UTC, Arsen6331 requested changes

2022-11-06 03:11 UTC, Arsen6331 commented on syncthing/lure.sh
> +checksums=('f91066b8588c02b5ff77aa801cc4e0319f3467325bdd75326aebccffb6495698')
Please change this to `checksums_amd64`

```suggestion
checksums_amd64=('f91066b8588c02b5ff77aa801cc4e0319f3467325bdd75326aebccffb6495698')
```

2022-11-06 03:12 UTC, Arsen6331 commented
Also, I've changed some things in this repo, so if you could merge those into your fork, that would be nice.

2022-11-07 07:21 UTC, xpamych commented
In fact, I planned to add the rest of the architectures later, they will have their own sources. Therefore, amd64 was explicitly specified so that the installation would not run on other architectures.

2022-11-07 07:49 UTC, Arsen6331 commented
> In fact, I planned to add the rest of the architectures later, they will have their own sources. Therefore, amd64 was explicitly specified so that the installation would not run on other architectures.

Yeah, but the `checksums` should have the same architecture as the `sources`, since they will be different for other architectures

2022-11-08 08:11 UTC, xpamych commented
i fix deps

2022-11-08 08:11 UTC, Arsen6331 approved these changes

2022-11-08 08:12 UTC, Arsen6331 commented
Thanks

2022-11-08 08:12 UTC, merged