upg(admc-git,jetbrains-toolbox-bin,noisetorch-bin,obsidian-bin,syncthing-relaysrv-bin):rename, upg(syncthing-bin):1.23.0, add(neofetch-bin,shfmt-git,telegram-desktop-bin)
Arsen6331/lure-repo pull request #34
Opened 2023-01-08 13:16 UTC by xpamych

Renamed the package according to [Package Conventions](https://github.com/Arsen6331/lure/blob/master/docs/packages/conventions.md). Added telegram-desktop-bin shfmt-git neofetch-bin discord-bin. syncthing updated to 1.23.0

2023-01-08 13:28 UTC, xpamych commented
Hmm, again, the formatting check does not pass, although both in the IDE and on github I see that everything is visually fine. Maybe I'm using the wrong [shfmt](https://github.com/patrickvane/shfmt.git)?

2023-01-08 18:28 UTC, Arsen6331 commented
> Hmm, again, the formatting check does not pass, although both in the IDE and on github I see that everything is visually fine. Maybe I'm using the wrong [shfmt](https://github.com/patrickvane/shfmt.git)?

Yeah, this is the one LURE uses: https://github.com/mvdan/sh/tree/master/cmd/shfmt

2023-01-08 18:50 UTC, Arsen6331 requested changes
Besides this, you seem to have accidentally changed the permissions for all the files in your PR. If you could please remove those changes, that would be great. While it wouldn't cause any issues, it would clutter the commit history with unnecessary changes. Thanks.

2023-01-08 18:50 UTC, Arsen6331 commented on admc-git/lure.sh
> +sources=("git+https://github.com/altlinux/${provides}.git")
Since the name of the repo isn't going to change, you can just hardcode it

```suggestion
sources=("git+https://github.com/altlinux/admc.git")
```

2023-01-08 18:50 UTC, Arsen6331 commented on discord-bin/lure.sh
> +	sed -i "s|Exec=/usr/share/discord/Discord|Exec=/opt/discord/${provides}|" ./Discord/${provides}.desktop
This seems like unneeded complexity as well as adding an extra dependency, when you could just install discord in `/usr/share/discord`. The location really doesn't matter for any distro.

2023-01-08 18:50 UTC, Arsen6331 commented on discord-bin/lure.sh
> +	find . -type d -exec install -d {,"${pkgdir}/opt/discord/"}{} \;
There's no need to do it this way, you can just copy the directory over

```suggestion
mkdir "${pkgdir}/opt"
cp -a "${srcdir}/Discord" "${pkgdir}/opt"
```

The `-a` option on `cp` preserves permissions, copies directories recursively, etc.

2023-01-08 18:50 UTC, Arsen6331 commented on telegram-desktop-bin/lure.sh
> +	install -dm755 "${pkgdir}/usr/share/applications/"
Just use `mkdir -p` if you're only creating directories.

```suggestion
	mkdir -p "${pkgdir}/usr/bin"
	mkdir -p "${pkgdir}/usr/share/pixmaps/"
	mkdir -p "${pkgdir}/usr/share/applications"
```

2023-01-08 18:50 UTC, Arsen6331 commented on obsidian-bin/lure.sh
> +	install -Dm755 "${scriptdir}/${provides}" "${pkgdir}/usr/bin/obsidian"
You should hard code the names here too, since they will not change

2023-01-09 08:05 UTC, closed without merging

2023-01-09 13:51 UTC, xpamych commented
thx for remarks. I have to work on it